name: Deploy Staging Website

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install  # or 'yarn install' if you use yarn

      - name: Build Staging
        run: npm run build  # or 'yarn build' if you use yarn

      - name: Deploy to Staging
        uses: actions/upload-artifact@v2
        with:
          name: staging
          path: build

      - name: Deploy to Staging Server
        uses: actions/aws/cli@v2
        with:
          args: s3 sync ./build/ s3://your-staging-bucket/ --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1  # Adjust to your S3 bucket's region
