image: node:16.17.1

pipelines:
  branches:
    staging:
      - step:
          name: Build and Deploy to S3
          size: 2x
          caches:
            - node
          script:
            - npm install
            - npm run build
            - apt-get update
            - apt-get install -y awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws configure set region us-east-1  # Update with your desired AWS region
            - aws s3 sync ./build/ s3://YOUR-STAGING-BUCKET-NAME/ --acl public-read
