name: Build and Sync to S3

on:
  push:
    branches:
      - staging

jobs:
  build_and_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Update with your desired AWS region
          
      - name: Deploy to Staging Server
        uses: actions/aws/cli@v2
        with:
          args: s3 sync ./build/ s3://${{ secrets.STAGING_BUCKET_NAME }}/ --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1  # Adjust to your S3 bucket's region
