name: Staging Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install  # or 'yarn install' if you use yarn

      - name: Build Staging
        run: npm run build  # or 'yarn build' if you use yarn

      - name: Deploy to Staging S3
        uses: actions/aws/cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your desired AWS region
          command: s3 sync ./build/ s3://$STAGING_BUCKET_NAME/ --acl public-read --delete
